name: Tests
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure CI Git User
        run: |
          git config --global user.name 'ruscon'
          git config --global user.email '27970303+ruscon@users.noreply.github.com'
          git remote set-url origin https://ruscon:$GITHUB_TOKEN@github.com/ruscon/nx-semantic-release-pnpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: '8.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm nx test nx-semantic-release-pnpm --runInBand --skip-nx-cache
